In [1]:
import numpy as np

In [5]:
#1
x = np.array([1, 2, 3, 4])
print("Original array:",x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))   #.all checks if there are any zeroes in an array
x = np.array([0, 1, 2, 3])
print("Original array:",x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array: [1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array: [0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [7]:
#2
x = np.array([0,1,2,3])
print("Original array:",x)
print("Test if none of the elements of the said array is zero:")
print(np.any(x))   #any checks if there are any non-zero values
x = np.array([0,0,0,0])
print("Original array:",x)
print("Test if none of the elements of the said array is zero:")
print(np.any(x))

Original array: [1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array: [0 0 0 0]
Test if none of the elements of the said array is zero:
False


In [11]:
#3
x=np.array([1,2,3,4,5])
y=np.array([1,2,3,4.00001,5])
print(x,y)  
print('equal:')
print(np.equal(x,y))
print('equal with tolerance')  #when it's said to be equal with tolerance????
print(np.allclose(x,y))


[1 2 3 4 5] [1.      2.      3.      4.00001 5.     ]
equal:
[ True  True  True False  True]
equal with tolerance
True


In [13]:
#4
a=np.zeros(10)
print("An array of 10 zeros:",a)
a=np.ones(10)
print("An array of 10 ones:",a)
a=np.ones(10)*5
print("An array of 10 fives:",a)

An array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [14]:
#5
a=np.arange(30,71)
print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [15]:
#6
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#7
a=np.random.normal(0,1,1) #.normal role?????
print(a)

[0.39909136]


In [23]:
#8
a=np.random.normal(0,1,15)
a

array([ 0.4842305 ,  1.19613898,  0.52020751,  0.38274252,  0.55098263,
       -1.79157842,  0.29809247,  0.88977382,  0.99507092, -0.70598866,
       -1.1625025 , -0.14628782,  1.86739553, -0.82348405, -0.29349283])

In [26]:
#9
a=np.arange(15,56)
print(a[0:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [28]:
#10
a=np.random.randint(0,10,5)
a

array([4, 9, 4, 7, 2])

In [37]:
#11
a=np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
#12
a=np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [40]:
#13
a = np.zeros((4, 4))
a[::2, 1::2] = 1
a[1::2, ::2] = 1
a
#???????????

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [41]:
#14
#?????????

In [47]:
#15
a=np.random.rand(40)
a

array([0.01390537, 0.58890993, 0.3829931 , 0.11481895, 0.86445401,
       0.82165703, 0.73749168, 0.84034417, 0.4015291 , 0.74862   ,
       0.55962945, 0.61323757, 0.29810165, 0.60237917, 0.42567684,
       0.53854438, 0.48672986, 0.49989164, 0.91745948, 0.26287702,
       0.04969769, 0.46269203, 0.40821902, 0.48704348, 0.07051578,
       0.58210861, 0.9870218 , 0.20908846, 0.21237612, 0.96113505,
       0.70695408, 0.59296821, 0.38085241, 0.6387405 , 0.50242857,
       0.08979307, 0.29717467, 0.82814423, 0.17545597, 0.90448946])

In [48]:
#16
a=np.array([1,2,3,4,5,6,7,8,9,10])
print("values bigger than 5:",a[a>5])

values bigger than 5: [ 6  7  8  9 10]
